updated docs to v1.10
OpenZeppelin/polkadot-generic-runtime-template pull request #166
Opened 2024-04-16 13:47 UTC by ozgunozerk

Fixes #165

2024-04-16 15:10 UTC, KitHat commented on docs/modules/ROOT/pages/pallets/assets.adoc
> +== Config
Both links were merged into one on line 9

2024-04-16 15:13 UTC, KitHat approved these changes

2024-04-16 15:13 UTC, ozgunozerk commented on docs/modules/ROOT/pages/pallets/assets.adoc
> +== Config
I can revert, but here is my reasoning: with each update, we have to go through all the links and update the lines. Not that helpful to other devs (they for sure can use `ctrl+f`), costs a lot of our time, and is very error prone.

So, I decided to give a single link (without lines). For me, it was a sweet spot.

2024-04-16 17:47 UTC, KitHat requested changes
I know, that it is out of scope for this PR, but @ozgunozerk could you please update the `docs/antora.yml` to be `Substrate Runtimes` instead of `Substrate Runtime`?
It will help us a lot during the integration to main docs site.

2024-04-16 18:07 UTC, ozgunozerk commented
Sure, but im afk at the moment. Shall we merge this and tomorrow morning i can create a PR for that? And it will be more granular? Or you can do it, however you please :)

2024-04-16 18:29 UTC, KitHat commented
It waits till tomorrow :)

2024-04-17 10:18 UTC, KitHat approved these changes
LGTM!

2024-04-17 10:18 UTC, merged